name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Toolchain
      run: |
        rustup default 1.80.1
        rustup component add clippy
        rustup component add rustfmt

    - name: Check format
      run: cargo fmt --check

    - name: Build
      run: cargo build --verbose

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
